project_name: "Slice TEMP" # template: ensure this gets updated when copying
output_dir: "Generated"
artifacts:
  - Schematic.pdf
  - PCB.pdf
  - kibot.log
  - BoM/*.html
images:
  - board_top.png
  - board_bottom.png
