title: Slice_TEMP # template: ensure this gets updated when copying
description: > # template: ensure this gets updated when copying
  A FEASTorg project page for SLICE.
baseurl: "/Slice_TEMP" # template: ensure this gets updated when copying
url: "https://feastorg.github.io"

remote_theme: pmarsceill/just-the-docs

footer_content: >
  <a href="https://feastorg.github.io">← Return to FEAST Main Site</a><br>
  Copyright © 2025 FEASTorg. MIT License.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

# Site/permalink settings useful for GitHub Pages docs
permalink: /:path/

# Don't publish these
exclude:
  - TODO.md
  - kibot/index_template.md
  - kibot/config.kibot.site.yml
  - README.md

# automatically apply layout: page to all docs/*.md
defaults:
  - scope:
      path: "" # everything under docs/
      type: "pages"
    values:
      layout: "page"

# Just the Docs theme settings
just_the_docs:
  logo:
    alt: "Slice TEMP" # template: ensure this gets updated when copying
  show_nav_level: 2
  collections:
    enable: false
